wget https://www.uniprot.org/uniprot/Q9RYM5.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/G3XCM7.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P71052.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q73JV3.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P76347.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P26649.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AF96.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AF45.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A8D6.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AEA2.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AE98.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ADU5.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ADT2.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ADS9.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AE95.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AE39.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P52106.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P31130.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P31129.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P52133.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P31058.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P76017.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q46840.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P64614.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ABK7.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P37016.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P09162.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0DMC7.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0DMC5.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P77432.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0DP21.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P28307.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AEB7.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q46919.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P77302.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P77300.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P45508.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q46865.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AAY6.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AAY1.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P64519.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AB49.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AB40.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AB35.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AB33.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AAR0.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P33340.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P64467.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P64442.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P39333.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75906.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q2FWJ1.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0C1U6.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q3BUB5.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/D3GYQ2.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KXW0.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KTL5.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ACE5.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0C0H0.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/O32266.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q57152.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/O50608.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/D3H539.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8PHY8.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q4TVQ0.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P43319.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P77172.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P69434.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P69432.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P32139.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P23874.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AAC0.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75994.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75993.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75992.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q47274.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75908.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75905.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P69348.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P69346.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P33997.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P05847.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75876.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75860.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75859.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75858.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P75855.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P17115.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q47150.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q47149.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/F2JXJ3.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q51380.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q4QNP7.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q4QNP6.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q4QNP5.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q4QNP4.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q4QNA8.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8DWM3.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/A7MNC7.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/A7MNC6.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q99039.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9RPY7.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8Y7I9.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8ZMD4.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q0WI08.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KRL4.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9X7H4.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9RLJ1.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/R9RWQ9.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/P39135.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/I4K5Z9.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q4QL77.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9HV98.fasta -O ->> ../uniprot_bioflim_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EGI4.fasta -O ->> ../uniprot_bioflim_seqs.fasta
