wget https://www.uniprot.org/uniprot/Q74G30.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q74G42.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EGR6.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8E9J0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9RX48.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I599.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I598.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I590.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I588.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I586.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I571.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I7A4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q817M5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I3Z8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q81FG5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q81FC3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P39753.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P39738.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P55891.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P64548.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A8Q0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P26649.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P26608.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P76237.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P76236.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P76204.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P76147.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P76010.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P37646.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ABY2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ABX8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ABX5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ABW9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AC47.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A9H9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P24216.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P52627.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P71301.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P39163.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P77333.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P46139.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0ABX2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AAY6.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P76330.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P39063.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A1I7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A1J1.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A1J9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P4Q4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P39752.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O67711.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KTL0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KQ07.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P65977.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q81FE8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P9B3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P9B4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P9B5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P9B6.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P9B8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9EWR3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q81FE1.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q81FE9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q81FF2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O25119.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I5G7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q1D4V8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A1J3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KQ08.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KQ10.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KQ11.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KQ63.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F951.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EYL7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/A5I572.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P76575.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0AAC0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P75942.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P75938.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P75936.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P75933.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P75914.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q47208.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KQ12.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P24073.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89I26.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P24501.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P24500.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89F28.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89ES5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89HY5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89JP4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O87127.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O87126.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P9B7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8P9C5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89NN8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89NY4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89NY7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q51460.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P16328.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P16437.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KL54.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9KQ09.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q92DU3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F2C6.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F2C5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F0W2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F0K4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F0B9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q81FE2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7UII2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7UJ26.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P96786.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O67244.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O67805.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8Y934.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8Y931.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CQR9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YK92.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YK89.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YIX4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YIG4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YIG3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YI47.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YI46.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CGK7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CGK9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YGA9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B4F159.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P23455.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P23451.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P23446.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9RPY7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CHX6.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CHZ9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7AP82.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8ZEW6.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8Y944.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8Y952.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O67836.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P96221.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O67006.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9X1M9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9X1M8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O67122.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9X185.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9X184.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9X0K7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/O67243.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9WZE3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9WZE1.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P16323.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8XA58.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89NY3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8ZP19.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89QF4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89I25.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89I12.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F0N8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q89F19.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A0S1.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P0A1I9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CIY9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CHY0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CHX9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CHX8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/B5YIX5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CGK6.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7CGK5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/P28611.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7UU79.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7UJ27.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7UII1.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7UNQ4.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7UNQ3.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q7ULV0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q92DV7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F532.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8F950.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9I4P7.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9I4P8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q748F0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q748H5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q748F1.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9I4Q2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9I4Q0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9I4P9.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q74G32.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EC99.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q748G5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q74G41.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9I4Q1.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q9K3C5.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EGF2.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8ECA8.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8ECA0.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EC97.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EC96.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EC95.fasta -O ->> ../uniprot_motility_seqs.fasta
wget https://www.uniprot.org/uniprot/Q8EC94.fasta -O ->> ../uniprot_motility_seqs.fasta
